### ISSUE TITLE
[researchers] researcher profile always kept in databae

### ISSUE THREAD

**Issue by anthonygego** [UCL-INGI/ictm-teaching#27]
When people are opt-out from research (via the `Is researcher` checkbox), the `Researcher` entry in database is preserved. This is not an optimal design as it allows incohenrency in database. Moreover, there is no relevance to have two distinct tables if they both lives the same time.

Initially, we wanted to build the researcher profile on top of the user profile. So in this model, the researcher profile is either existing or not, and a user is a researcher if such an entry exists.

Keeping research profile in the same table is another solution but less elegant as it increases data sparsity.

**Comment by SamuelVch98** [comment]
I'm not sure I fully understand what it means to build the researcher's profile on top of the user's profile. The ‘New User’ page would only allow a user to be created and a new page would allow a researcher to be created and linked to a user?
